apiVersion: v1
kind: Service
metadata:
  name: ping-pong
spec:
  type: NodePort
  selector:
    app: PingPong
    deployment: ${DEPLOY_VERSION}  # blue or green
  ports:
  - port: 80
    targetPort: 8001
